"""helpers for web scrapping"""
from helpers.tg import TgHelper
from helpers.chapter import Chapter
from helpers.base import BaseHelper
from helpers.cocomanhua import CocomanhuaHelper
from helpers.wutuxs import WutuxsHelper
from helpers.manhuagui import ManhuaguiHelper
from helpers.esjzone import EsjzoneHelper
from helpers.syosetu import SyosetuHelper
from helpers.qiman6 import Qiman6Helper
from helpers.baozimh import BaozimhHelper
