- name: 舔狗生肉
  novel_urls:
    - https://ncode.syosetu.com/n6621fl
    - https://masiro.me/admin/novelView?novel_id=212
- name: 不知我的死亡flag將於何處停止
  novel_urls:
    - https://ncode.syosetu.com/n4449cj
    - https://tieba.baidu.com/f?kw=%E4%B8%8D%E7%9F%A5%E6%88%91%E7%9A%84%E6%AD%BB%E4%BA%A1flag%E5%B0%86%E4%BA%8E%E4%BD%95%E5%A4%84%E5%81%9C%E6%AD%A2&ie=utf-8&tp=0
# - name: 悲劇元兇的最強外道BOSS女王為民竭力
#   novel_urls:
#     - https://www.esjzone.cc/detail/1591099430.html
# - name: 輪迴第7次的反派千金
#   novel_urls:
#     - https://www.esjzone.cc/detail/1584472487.html
# - name: 聖女大人想狂寵但是勇者、你還不行漫畫
#   novel_urls:
#     - https://www.esjzone.cc/detail/1609121231.html
- name: 鄰家的天使大人
  novel_urls:
    - https://ncode.syosetu.com/n8440fe
    - https://masiro.me/admin/novelView?novel_id=9

- name: 虛構推理
  comic_urls:
    - https://m.manhuagui.com/comic/17165/
    - https://www.dm5.com/manhua-xugoutuili/
- name: 石紀元
  comic_urls:
    - https://m.manhuagui.com/comic/23270/
- name: 總之就是非常可愛
  comic_urls:
    - https://m.manhuagui.com/comic/27099/
# - name: 獨自一人的異世界攻略
#   comic_urls:
#     - https://m.manhuagui.com/comic/30903/
# - name: 請在伸展台上微笑
#   comic_urls:
#     - https://m.manhuagui.com/comic/24255/
# - name: 戀愛禁止的世界
#   comic_urls:
#     - https://m.manhuagui.com/comic/14162/
- name: 宅男腐女戀愛真難
  comic_urls:
    - https://m.manhuagui.com/comic/17217/
# - name: 平凡职业成就世界最强 零
#   comic_urls:
#     - https://m.manhuagui.com/comic/28024/
# - name: 輝夜大小姐想讓我告白
#   comic_urls:
#     - https://m.manhuagui.com/comic/17332/
#     - http://qiman59.com/19827/
# - name: 葬送的芙莉蓮
#   comic_urls:
#     - https://m.manhuagui.com/comic/35937/
# - name: 我立于百萬生命之上
#   comic_urls:
#     - https://m.manhuagui.com/comic/20667/
# - name: 碧藍之海
#   comic_urls:
#     - https://m.manhuagui.com/comic/12887/
# - name: 詛咒裝備
#   comic_urls:
#     - https://m.manhuagui.com/comic/32271/
# - name: 我推的孩子
#   comic_urls:
#     - https://m.manhuagui.com/comic/35634/
# - name: 夜櫻家的大作戰
#   comic_urls:
#     - https://m.manhuagui.com/comic/33232/
# - name: 從廢柴判定開始的魔術士人生
#   comic_urls:
#     - https://m.manhuagui.com/comic/35450/
# - name: 異劍戰記Völundio
#   comic_urls:
#     - https://m.manhuagui.com/comic/37432/
- name: 摺紙戰士A
  comic_urls:
    - https://m.manhuagui.com/comic/41682/
- name: 最強肉盾的迷宮攻略～擁有稀少技能體力9999的肉盾
  comic_urls:
    - https://m.manhuagui.com/comic/49573/
    - https://www.novelcool.com/novel/Saikyou-Tank-no-Meikyuu-Kouryaku.html

- name: SSS級自殺獵人
  comic_urls:
    - https://kunmanga.com/manga/sss-class-suicide-hunter/
    - https://www.baozimh.com/comic/sssjizishaxiren-shinnoahsinnoaneidaneidabillk_r
    - https://kunmanga.com/manga/sss-class-suicide-hunter/
# - name: 元尊
#   novel_urls:
#     - https://www.99wx.cc/yuanzun/
#     - http://www.wutuxs.com/html/7/7876/
#   comic_urls:
#     - https://www.baozimh.com/comic/yuanzun-weitianchuanmei_q3py2w
#     - https://www.99wx.cc/manhua/yuanzun/
#     - http://qiman59.com/12780/
# - name: 萬相之王
#   novel_urls:
#     - https://www.99wx.cc/wanxiangzhiwang/
#     - http://www.wutuxs.com/html/9/9715/
#   comic_urls:
#     - https://www.baozimh.com/comic/moxiangzhiwang-weitianchuanmei
#     - https://www.99wx.cc/manhua/wanxiangzhiwang/
#     - http://qiman59.com/24453/
# - name: 仙帝歸来
#   comic_urls:
#     - http://qiman59.com/12235/
# - name: 英雄？我早就不當了
#   comic_urls:
#     - https://www.baozimh.com/comic/yingxiongzailinyingxiongwozaojiubudangliao-sfqingxiaoshuo_yuls6q
#     - http://qiman59.com/17128/
# - name: 撿個校花做老婆
#   comic_urls:
#     - http://qiman59.com/11952/
# - name: 萬古神王
#   comic_urls:
#     - http://qiman59.com/17384/
- name: 失業魔王
  comic_urls:
    - https://www.baozimh.com/comic/shiyemowang-sfqingxiaoshuo
    - http://qiman59.com/16793/
# - name: 修真聊天群
#   comic_urls:
#     - http://qiman59.com/9454/
- name: 我家大師兄腦子有坑
  comic_urls:
    - https://www.baozimh.com/comic/wojiadashixiongnaoziyoukeng-juxiangmanhua_9c6rg8
    - http://qiman59.com/12624/
# - name: 我的女徒弟們都是未來諸天大佬
#   comic_urls:
#     - https://www.baozimh.com/comic/wodenutudimendushiweilaizhutiandalao-sfqingxiaoshuo
#     - http://qiman59.com/24583/
- name: 史上最強男主角
  comic_urls:
    - https://www.baozimh.com/comic/shishangzuiqiangnanzhujiao-taxuedongman
    - http://qiman59.com/24334/
    - https://www.colamanga.com/manga-rq384584/
- name: 放開那個女巫
  comic_urls:
    - https://www.baozimh.com/comic/fangkainagenuwu-yuewenmanhua_e
    - http://qiman59.com/15437/
    - https://www.colamanhua.com/manga-yi73804/
- name: 我的師父什麽都懂億點點
  novel_urls:
    - https://www.piaotia.com/html/14/14565/
- name: 我家老婆来自一千年前
  comic_urls:
    - https://www.baozimh.com/comic/wojialaopolaiziyiqiannianqian-yuewenmanhua
    - https://www.colamanga.com/manga-ad81146/
- name: 我真沒想重生啊
  comic_urls:
    - https://www.baozimh.com/comic/wozhenmeixiangzhongshenga-pikapi
    - https://www.colamanga.com/manga-mf955567/
- name: 頂級氣運，悄悄修煉千年
  comic_urls:
    - https://www.baozimh.com/comic/dingjiqiyunqiaoqiaoxiulianqiannian-yuewenmanhua
    - https://www.colamanga.com/manga-rl19867/
- name: 小师妹明明超强却过分沙雕
  comic_urls:
    - https://baozimh.org/manga/xiaoshimeimingmingchaoqiangqueguofenshadiao
    - https://www.colamanga.com/manga-ds844890/
- name: 给妹妹陪读的我，不小心无敌了
  comic_urls:
    - https://baozimh.org/manga/geimeimeipeidudewobuxiaoxinwudile
    - https://www.colamanga.com/manga-ii712602/
- name: 女主从书里跑出来了怎么办
  comic_urls:
    - https://baozimh.org/manga/nvzhucongshulipaochulailezenmeban
    - https://www.colamanga.com/manga-oh587803/
