name: Python Unit Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Update dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install Cython
        run: python -m pip install cython
      - name: Test
        uses: onichandame/python-test-action@master
